Repository Ureca-Final-Project-Team1/UFO-Fi-FE, pull requests merged in 2025-07, with the labels that each got.

#28 UF-67 Typography 추가 및 의존성 주입
  package-lock.json
  package.json
  public/fonts/PretendardVariable.woff2
  src/app/layout.tsx
  src/styles/globals.css
Labels: enhancement

#37 UF-72 컴포넌트에 Switch 추가
  package-lock.json
  package.json
  src/components/ui/Switch/Switch.stories.tsx
  src/components/ui/Switch/Switch.tsx
  src/components/ui/Switch/index.ts
Labels: enhancement

#41 UF-74 Chromatic을 활용한 Storybook 배포 워크플로우 구축
  .github/workflows/chromatic.yml
  package-lock.json
  package.json
Labels: enhancement

#26 UF-65 Radio 및 Label 컴포넌트 추가
  package-lock.json
  package.json
  src/components/ui/Label/Label.stories.tsx
  src/components/ui/Label/Label.tsx
  src/components/ui/Label/Label.types.ts
  src/components/ui/Label/index.ts
  src/components/ui/Label/labelVariants.ts
  src/components/ui/Radio/Radio.stories.tsx
  src/components/ui/Radio/Radio.types.ts
  src/components/ui/Radio/RadioGroup.tsx
  src/components/ui/Radio/RadioGroupItem.tsx
  src/components/ui/Radio/index.ts
  src/components/ui/Radio/radioVariants.ts
  src/components/ui/index.ts
Labels: enhancement

#32 UF-68 components에 sonner 추가
  package-lock.json
  package.json
  src/app/page.tsx
  src/components/ui/Sonner/Sonner.stories.tsx
  src/components/ui/Sonner/Sonner.tsx
  src/components/ui/Sonner/index.ts
  src/components/ui/index.ts
Labels: enhancement

#29 UF-64 Select 컴포넌트 추가
  src/components/ui/Select/Select.stories.tsx
  src/components/ui/Select/Select.tsx
  src/components/ui/Select/Select.types.ts
  src/components/ui/Select/index.ts
  src/components/ui/Select/selectVariants.ts
  src/components/ui/index.ts
Labels: enhancement

#36 UF-71 Badge 컴포넌트 추가
  src/components/ui/Badge/Badge.stories.tsx
  src/components/ui/Badge/Badge.tsx
  src/components/ui/Badge/Badge.types.ts
  src/components/ui/Badge/badgeVariants.ts
  src/components/ui/Badge/index.ts
  src/components/ui/index.ts
  src/styles/globals.css
Labels: enhancement

#39 UF-70 Icon 컴포넌트 구현
  public/icons/astronut.svg
  public/icons/planet.svg
  src/components/ui/Icons/CustomIcons.tsx
  src/components/ui/Icons/Icon.tsx
  src/components/ui/Icons/IconWrapper.tsx
  src/components/ui/Icons/Icons.stories.tsx
  src/components/ui/Icons/Icons.types.ts
  src/components/ui/Icons/ImageIcon.tsx
  src/components/ui/Icons/LucideIcon.tsx
  src/components/ui/Icons/index.ts
  src/components/ui/index.ts
  src/constants/icons.ts
Labels: enhancement

#51 UF-66 네비게이션 포함한 레이아웃 컴포넌트 1차 구현
  public/icons/ufo-logo.svg
  src/app/exchange/page.tsx
  src/app/layout.tsx
  src/app/main/page.tsx
  src/app/market/page.tsx
  src/app/mypage/page.tsx
  src/app/page.tsx
  src/app/sell/page.tsx
  src/components/layout/BottomNav/BottomNav.tsx
  src/components/layout/BottomNav/BottomNav.types.ts
  src/components/layout/BottomNav/index.ts
  src/components/layout/TopNav/TopNav.tsx
  src/components/layout/TopNav/TopNav.types.ts
  src/components/layout/TopNav/index.ts
  src/components/ui/Icons/CustomIcons.tsx
  src/components/ui/Icons/Icon.tsx
  src/components/ui/Icons/Icons.stories.tsx
  src/components/ui/Icons/Icons.types.ts
  src/components/ui/Icons/ImageIcon.tsx
  src/constants/icons.ts
  src/hooks/useNavigation.ts
  src/styles/globals.css
Labels: enhancement

#58 UF-86 DotBadge 컴포넌트 스토리북 추가
  src/components/ui/DotBadge/DotBadge.stories.tsx
  src/components/ui/DotBadge/DotBadge.tsx
  src/components/ui/DotBadge/DotBadge.types.ts
  src/components/ui/DotBadge/dotBadgeVariants.ts
  src/components/ui/DotBadge/index.ts
  src/components/ui/index.ts
Labels: enhancement

#55 UF-84 Modal 컴포넌트 및 전역 상태 관리 구현
  .storybook/preview-head.html
  public/images/alien-happy.png
  public/images/alien-sad.png
  src/app/layout.tsx
  src/components/ui/Modal/GlobalModal.stories.tsx
  src/components/ui/Modal/GlobalModal.tsx
  src/components/ui/Modal/Modal.stories.tsx
  src/components/ui/Modal/Modal.tsx
  src/components/ui/Modal/Modal.types.ts
  src/components/ui/Modal/index.ts
  src/components/ui/Modal/modalVariants.ts
  src/components/ui/index.ts
  src/constants/images.ts
  src/hooks/useModal.ts
  src/provider/ModalProvider.tsx
  src/provider/index.ts
  src/stores/useModalStore.ts
Labels: enhancement

#62 UF-83 Title 컴포넌트 구현
  src/components/ui/Icons/Icon.tsx
  src/components/ui/Icons/Icons.types.ts
  src/components/ui/Title/Title.stories.tsx
  src/components/ui/Title/Title.tsx
  src/components/ui/Title/Title.types.ts
  src/components/ui/Title/index.ts
  src/components/ui/Title/titleVariants.ts
  src/components/ui/index.ts
Labels: enhancement

#61 UF-63 button component 구현
  src/components/ui/Button/Button.stories.tsx
  src/components/ui/Button/Button.tsx
  src/components/ui/Button/Button.types.ts
  src/components/ui/Button/buttonVariants.ts
  src/components/ui/Button/index.ts
  src/components/ui/Icons/CustomIcons.tsx
  src/components/ui/Icons/Icon.tsx
  src/components/ui/Icons/Icons.types.ts
  src/styles/globals.css
Labels: enhancement

#68 UF-91 Indicator 컴포넌트 구현 및 스토리북 제작
  src/components/ui/Indicator/Indicator.stories.tsx
  src/components/ui/Indicator/Indicator.tsx
  src/components/ui/Indicator/Indicator.types.ts
  src/components/ui/Indicator/index.ts
  src/components/ui/Indicator/indicatorVariants.ts
  src/components/ui/index.ts
Labels: enhancement

#71 UF-96 Modal 내 button을 Button 컴포넌트로 교체
  src/components/ui/Modal/Modal.tsx
  src/components/ui/Modal/modalVariants.ts
Labels: enhancement

#85 UF-111 Navigation Provider 제작
  src/app/layout.tsx
  src/app/onboarding/page.tsx
  src/constants/routes.ts
  src/hooks/useOnboardingGuard.ts
  src/lib/onboarding.ts
  src/middleware.ts
  src/provider/BackgroundProvider.tsx
  src/provider/NavigationProvider.tsx
  src/provider/OnboardingGuardProvider.tsx
Labels: enhancement

#80 UF-106 Chip 컴포넌트 추가
  src/components/ui/Chip/Chip.stories.tsx
  src/components/ui/Chip/Chip.tsx
  src/components/ui/Chip/Chip.types.ts
  src/components/ui/Chip/index.ts
  src/components/ui/Icons/Icons.types.ts
Labels: enhancement

#81 UF-99 전역 사용 가능한 skeleton component 구현
  src/components/ui/Skeleton/Skeleton.stories.tsx
  src/components/ui/Skeleton/Skeleton.tsx
  src/components/ui/Skeleton/index.ts
Labels: enhancement

#93 UF-118 api 테스트 성공
  src/app/signup/plan/page.tsx
  src/app/signup/privacy/page.tsx
  src/lib/axios.ts
Labels: enhancement

#91 UF-73 임시 Tab 컴포넌트 구현
  src/components/ui/Tabs/Tabs.stories.tsx
  src/components/ui/Tabs/Tabs.tsx
  src/components/ui/Tabs/Tabs.types.ts
  src/components/ui/Tabs/index.ts
  src/components/ui/Tabs/tabsVariants.ts
Labels: enhancement

#97 UF-112 rename input components (i 대문자로 변경)
  src/app/signup/profile/page.tsx
  src/components/ui/Input/AccountInput.tsx
  src/components/ui/Input/BankSelectInput.tsx
  src/components/ui/Input/BasicInput.tsx
  src/components/ui/Input/Input.stories.tsx
  src/components/ui/Input/Input.tsx
  src/components/ui/Input/Input.types.ts
  src/components/ui/Input/LabeledInput.tsx
  src/components/ui/Input/PhoneInput.tsx
  src/components/ui/Input/PriceInput.tsx
  src/components/ui/Input/inputVariants.ts
Labels: enhancement

#107 UF-132 signup API 연동
  src/api/signup/getPlansByTelecom.ts
  src/api/signup/signupWithPlan.ts
  src/api/types/SignupWithPlanTypes.ts
  src/app/login/page.tsx
  src/app/signup/plan/page.tsx
  src/app/signup/privacy/page.tsx
  src/app/signup/profile/page.tsx
  src/schemas/signupSchema.ts
  src/shared/types/plan.ts
  src/stores/useSignupStore.ts
Labels: enhancement

#111 UF-134 style 수정 및 props 명칭 변경
  src/api/signup/getPlansByTelecom.ts
  src/api/signup/signupWithPlan.ts
  src/api/signup/types/SignupWithPlanTypes.ts
  src/app/signup/plan/page.tsx
  src/app/signup/profile/page.tsx
  src/provider/BackgroundProvider.tsx
  src/schemas/signupSchema.ts
  src/stores/useSignupStore.ts
Labels: enhancement

#112 UF-131 404 not found 페이지 구현
  package-lock.json
  public/images/not-found.png
  public/images/warning.png
  src/app/not-found.tsx
  src/constants/images.ts
Labels: enhancement

#133 UF-153 ZET 코인 구매 페이지 구현
  public/images/package-A.png
  public/images/package-B.png
  public/images/package-C.png
  public/images/package-D.png
  public/images/package-E.png
  src/app/charge/page.tsx
  src/constants/images.ts
  src/constants/packages.ts
  src/features/charge/components/ZetChargePackageCard.tsx
  src/styles/globals.css
Labels: enhancement

#138 UF-166 add payment modal components
  public/images/alien-sowhat.svg
  public/images/alien-wrong.svg
  src/constants/images.ts
  src/features/payment/components/InsufficientZetModal.stories.tsx
  src/features/payment/components/InsufficientZetModal.tsx
  src/features/payment/components/PaymentCancellationModal.stories.tsx
  src/features/payment/components/PaymentCancellationModal.tsx
  src/features/payment/components/SimplePasswordModal.stories.tsx
  src/features/payment/components/SimplePasswordModal.tsx
  src/shared/ui/Modal/Modal.tsx
  src/shared/ui/Modal/Modal.types.ts
  src/shared/ui/Modal/modalVariants.ts
Labels: enhancement

#143 UF-160 임시 알림 필터링 페이지 제작
  src/app/exchange/notification/page.tsx
  src/features/exchange/components/FilterBox.tsx
  src/features/exchange/types/FilterBoxProps.ts
  src/features/mypage/components/TradeHistoryCard.stories.tsx
  src/hooks/useFilterState.ts
  src/hooks/useFilteredItemCount.ts
  src/shared/ui/Icons/Icons.types.ts
  src/shared/ui/Slider/DataRangeSlider.tsx
  src/shared/ui/Slider/DataSlider.tsx
  src/shared/ui/Slider/Slider.types.ts
  src/styles/globals.css
  src/utils/sliderUtils.ts
Labels: enhancement

#146 UF-158 마이페이지 팔로우 목록 페이지 추가
  src/app/mypage/follow/page.tsx
  src/features/mypage/follow/components/FollowItem.tsx
  src/features/mypage/follow/components/FollowTabContent.tsx
  src/features/mypage/follow/components/index.ts
  src/features/mypage/follow/types/FollowType.types.ts
  src/shared/ui/Button/Button.stories.tsx
  src/shared/ui/Button/Button.types.ts
  src/shared/ui/Button/buttonVariants.ts
  src/shared/ui/index.ts
Labels: enhancement

#157 UF-180 결제 간편 비밀번호 페이지,컴포넌트 추가
  src/app/payment/password/page.tsx
  src/features/payment/components/NumberButton.tsx
  src/features/payment/components/PasswordInput.tsx
  src/features/payment/components/PasswordPad.tsx
  src/features/payment/types/PasswordPad.types.ts
  src/provider/BackgroundProvider.tsx
  src/styles/globals.css
Labels: enhancement

#173 UF-128부모 크기에 맞게 슬라이더 가변하도록 구현
  src/shared/ui/Slider/DataSlider.tsx
Labels: enhancement

#161 UF-182 이용 약관, 개인정보처리방침 구현
  next.config.ts
  package-lock.json
  package.json
  src/app/mypage/privacy/layout.tsx
  src/app/mypage/privacy/page.tsx
  src/app/mypage/service/layout.tsx
  src/app/mypage/service/page.tsx
  src/assets/terms/privacy.md
  src/assets/terms/service.md
  src/shared/utils/termsRenderer.tsx
  src/types/markdown.d.ts
Labels: enhancement

#182 UF-198 axiosInstance 수정
  src/api/client/axios.ts
Labels: enhancement

#168 UF-191 PlanCombo 구현
  package-lock.json
  package.json
  src/features/signup/components/PlanCombo/PlanCombo.stories.tsx
  src/features/signup/components/PlanCombo/PlanCombo.tsx
  src/features/signup/components/PlanCombo/PlanCombo.types.ts
  src/features/signup/components/PlanCombo/index.ts
  src/features/signup/components/PlanCombo/planComboVariants.ts
  src/features/signup/components/index.ts
  src/shared/ui/Command/Command.stories.tsx
  src/shared/ui/Command/Command.tsx
  src/shared/ui/Command/Command.types.ts
  src/shared/ui/Command/index.ts
  src/shared/ui/Dialog/Dialog.stories.tsx
  src/shared/ui/Dialog/Dialog.tsx
  src/shared/ui/Dialog/Dialog.types.ts
  src/shared/ui/Dialog/dialogVariants.ts
  src/shared/ui/Dialog/index.ts
  src/shared/ui/Icons/Icons.stories.tsx
  src/shared/ui/Icons/Icons.types.ts
  src/shared/ui/index.ts
Labels: enhancement

#186 UF-176 refactor title back navigation
  src/app/blackhole/page.tsx
  src/app/charge/page.tsx
  src/app/mypage/follow/page.tsx
  src/app/mypage/privacy/page.tsx
  src/app/mypage/service/page.tsx
  src/app/payment/password/page.tsx
  src/shared/ui/Title/Title.tsx
  src/shared/ui/Title/Title.types.ts
Labels: enhancement

#199 UF-209 FCM 토큰 저장 및 필터링을 통한 알림 조건 설정 API 연동
  src/api/index.ts
  src/api/services/fcm/token.ts
  src/api/types/carrier.ts
  src/api/types/fcm.ts
  src/app/api/fcm/send-test/route.ts
  src/app/exchange/notification/page.tsx
  src/app/layout.tsx
  src/app/login/success/page.tsx
  src/app/test/fcm/page.tsx
  src/hooks/useNotification.ts
  src/lib/auth.ts
  src/lib/fcm.ts
  src/shared/components/FCMProvider.tsx
  src/shared/components/NotificationSettings.tsx
  src/shared/ui/Title/Title.tsx
Labels: enhancement

#218 UF-226 purchase API 구현
  src/api/bulk/search/[searchId]/route.ts
  src/api/bulk/search/route.ts
  src/api/services/exchange/bulkPurchase.ts
  src/api/services/exchange/purchase.ts
  src/api/types/exchange.ts
  src/features/bulk/components/BulkResultContent.tsx
Labels: enhancement

#220 UF-227 로그인 분기 추가
  src/api/services/auth/role.ts
  src/api/types/role.ts
  src/app/login/page.tsx
  src/app/login/success/page.tsx
  src/app/signup/plan/page.tsx
  src/app/signup/profile/page.tsx
  src/features/signup/components/PlanCombo/PlanCombo.tsx
  src/schemas/signupSchema.ts
Labels: enhancement

#179 UF-185 판매/구매 내역 api 구현
  src/api/services/history/purchaseHistory.ts
  src/api/services/history/sellHistory.ts
  src/api/types/history.ts
  src/app/mypage/trade/page.tsx
  src/features/mypage/types/TradeHistoryCard.types.ts
  src/hooks/useTradeHistory.ts
  src/utils/groupByDate.ts
Labels: enhancement

#211 UF-221 Carrier 타입 string → enum Carrier로 프로젝트 전체 일괄 적용
  src/api/types/auth.ts
  src/api/types/exchange.ts
  src/api/types/plan.ts
  src/app/exchange/types/exchange.types.ts
  src/app/signup/plan/page.tsx
  src/features/bulk/components/BulkResultCard.tsx
  src/features/bulk/components/BulkResultContent.tsx
  src/features/bulk/hooks/useBulkResult.ts
  src/features/bulk/types/bulkResult.types.ts
  src/features/exchange/components/SellingItem.tsx
  src/features/mypage/components/TradeHistoryCard.stories.tsx
  src/stores/useSignupStore.ts
Labels: enhancement

#222 UF-208 마이페이지 내 정보 수정 api 추가
  src/api/client/axios.ts
  src/api/index.ts
  src/api/services/mypage/editProfile.ts
  src/app/mypage/edit-profile/page.tsx
  src/features/mypage/components/ConfirmModal.tsx
  src/features/mypage/components/NicknameEditor.tsx
  src/features/mypage/components/PlanEditor.tsx
  src/features/mypage/components/SignalCard.tsx
  src/features/mypage/components/index.ts
  src/features/mypage/hooks/useEditProfile.tsx
Labels: enhancement

#237 UF-205 충전 요청 API 구현 및 토스페이먼츠 연동
  package-lock.json
  package.json
  src/api/index.ts
  src/api/services/payment/charge.ts
  src/api/types/payment.ts
  src/app/charge/page.tsx
  src/app/payment/fail/page.tsx
  src/app/payment/success/page.tsx
  src/features/charge/components/ZetChargePackageCard.tsx
  src/features/charge/hooks/useTossPayments.ts
  src/features/charge/hooks/useZetCharge.ts
  src/features/exchange/components/ExchangeList.tsx
  src/utils/uuid.ts
Labels: enhancement

#235 UF-235 signup 페이지 수정
  src/app/signup/plan/page.tsx
  src/app/signup/profile/page.tsx
  src/app/test/ocr/page.tsx
  src/features/signup/components/PlanCombo/PlanCombo.tsx
  src/features/signup/components/PlanCombo/PlanCombo.types.ts
  src/features/signup/components/Stepper/Stepper.stories.tsx
  src/features/signup/components/Stepper/Stepper.tsx
  src/features/signup/components/Stepper/Stepper.types.ts
  src/features/signup/components/Stepper/index.ts
  src/features/signup/components/index.ts
  src/hooks/useOCRToGptMutation.ts
  src/service/ocrToGptService.ts
  src/shared/ui/Icons/Icons.types.ts
  src/stores/useSignupStore.ts
  src/styles/components/typography.css
  src/styles/globals.css
  src/types/ocr.ts
  src/utils/OCRPrompt.ts
Labels: enhancement

#240 UF-238 로그아웃 시 모달 팝업
  src/app/mypage/page.tsx
  src/features/mypage/components/LogoutModal.tsx
  src/features/mypage/components/index.ts
Labels: enhancement

#247 UF-234 프로필 조회 및 공유 기능 구현
  next.config.ts
  package-lock.json
  package.json
  src/api/index.ts
  src/api/services/profile/profile.ts
  src/api/types/profile.ts
  src/app/profile/[userId]/datalist/page.tsx
  src/app/profile/[userId]/layout.tsx
  src/app/profile/[userId]/loading.tsx
  src/app/profile/[userId]/page.tsx
  src/features/profile/components/DataListView/SimpleDataCard.tsx
  src/features/profile/components/DataListView/index.tsx
  src/features/profile/components/ProfileShare/ProfileShareContent.tsx
  src/features/profile/components/ProfileShare/QRCodeGenerator.tsx
  src/features/profile/components/ProfileShare/ShareButtons.tsx
  src/features/profile/components/ProfileShare/ShareModal.tsx
  src/features/profile/components/ProfileShare/index.tsx
  src/features/profile/components/ProfileView/ProfileContentSections.tsx
  src/features/profile/components/ProfileView/ProfileHeader.tsx
  src/features/profile/components/ProfileView/ProfileStats.tsx
  src/features/profile/components/ProfileView/TradeData.tsx
  src/features/profile/components/ProfileView/index.tsx
  src/features/profile/hooks/useKakaoSDK.ts
  src/features/profile/hooks/useProfile.ts
  src/features/profile/hooks/useProfileShare.ts
  src/features/profile/hooks/useWebShare.ts
  src/features/profile/stories/ProfileShare.stories.tsx
  src/features/profile/stories/ProfileView.stories.tsx
  src/features/profile/stories/ShareButtons.stories.tsx
  src/features/profile/utils/qrCodeUtils.ts
  src/features/profile/utils/shareUtils.ts
  src/features/profile/utils/socialShare.ts
  src/shared/types/kakao.ts
  src/shared/ui/Icons/Icons.types.ts
  src/shared/ui/UserLink/index.tsx
Labels: enhancement

#248 UF-225 백오피스 레이아웃 그리드 시스템 적용 및 메뉴별 UI 페이지 구현
  src/app/admin/banned-words/page.tsx
  src/app/admin/page.tsx
  src/app/admin/posts/page.tsx
  src/app/admin/posts/reported/page.tsx
  src/app/admin/settings/page.tsx
  src/app/admin/user/inactive/page.tsx
  src/app/admin/user/page.tsx
  src/provider/BackgroundProvider.tsx
  src/shared/ui/Header/Header.tsx
  src/shared/ui/Icons/Icons.types.ts
  src/shared/ui/Sidebar/Sidebar.tsx
Labels: enhancement

#254 UF-242 데이터 구매 시 보여지는 데이터 전송과정 안내 페이지 추가 1차안 (UI 수정 계획 있음)
  public/images/alien-serious-reported.png
  public/images/alien-serious-reported.svg
  public/images/data-cube.svg
  public/images/purchase-coin.svg
  public/images/purchase-completed.svg
  src/app/exchange/page.tsx
  src/app/exchange/purchase/[id]/page.tsx
  src/app/exchange/purchase/[id]/step1/page.tsx
  src/app/exchange/purchase/[id]/step2/page.tsx
  src/app/exchange/purchase/[id]/step3/page.tsx
  src/constants/images.ts
  src/features/exchange/components/ExchangeHeader.tsx
Labels: enhancement

#260 UF-252 테이블 컴포넌트에 페이지네이션 기능 추가
  src/features/user-management/components/UserTable.tsx
  src/shared/hooks/usePagination.ts
  src/shared/ui/Pagination/Pagination.tsx
  src/shared/ui/Table/Table.stories.tsx
  src/shared/ui/Table/Table.tsx
Labels: enhancement

#264 UF-256 carousel을 통한 profile 제작
  package-lock.json
  package.json
  src/app/api/collections/route.ts
  src/app/api/collections/search/route.ts
  src/app/test/page.tsx
  src/features/profile/components/Carousel/EmblaCarousel.tsx
  src/features/profile/components/Carousel/EmblaCarousel.types.tsx
  src/features/profile/components/Carousel/EmblaCarouselArrowButtons.tsx
  src/features/profile/components/Carousel/index.tsx
  src/shared/ui/Icons/CustomIcons.tsx
  src/shared/ui/Icons/Icons.types.ts
Labels: enhancement

#256 UF-249 Title 컴포넌트 스토리북 호환성 개선
  src/app/blackhole/page.tsx
  src/app/charge/page.tsx
  src/app/exchange/bulk/page.tsx
  src/app/exchange/bulk/result/index.tsx
  src/app/exchange/notification/page.tsx
  src/app/mypage/edit-profile/page.tsx
  src/app/mypage/follow/page.tsx
  src/app/mypage/privacy/page.tsx
  src/app/mypage/service/page.tsx
  src/app/payment/password/page.tsx
  src/app/sell/edit/[id]/page.tsx
  src/features/bulk/components/BulkResultContent.tsx
  src/features/common/components/TitleWithRouter.tsx
  src/features/profile/components/DataListView/index.tsx
  src/features/profile/components/ProfileShare/ShareButtons.tsx
  src/features/profile/components/ProfileView/index.tsx
  src/shared/ui/Title/Title.tsx
  src/shared/ui/Title/index.ts
Labels: bug, enhancement

#275 UF-246 백오피스 개발을 위한 테이블 컴포넌트 리팩토링
  package-lock.json
  package.json
  src/app/admin/banned-words/page.tsx
  src/app/admin/posts/page.tsx
  src/app/admin/posts/reported/page.tsx
  src/app/admin/user/inactive/page.tsx
  src/app/api/collections/route.ts
  src/app/api/collections/search/route.ts
  src/app/blackhole/page.tsx
  src/app/charge/page.tsx
  src/app/exchange/bulk/page.tsx
  src/app/exchange/bulk/result/index.tsx
  src/app/exchange/notification/page.tsx
  src/app/layout.tsx
  src/app/mypage/edit-profile/page.tsx
  src/app/mypage/follow/page.tsx
  src/app/mypage/privacy/page.tsx
  src/app/mypage/service/page.tsx
  src/app/payment/password/page.tsx
  src/app/sell/edit/[id]/page.tsx
  src/app/test/page.tsx
  src/features/bulk/components/BulkResultContent.tsx
  src/features/common/components/TitleWithRouter.tsx
  src/features/profile/components/Carousel/EmblaCarousel.tsx
  src/features/profile/components/Carousel/EmblaCarousel.types.tsx
  src/features/profile/components/Carousel/EmblaCarouselArrowButtons.tsx
  src/features/profile/components/Carousel/index.tsx
  src/features/profile/components/DataListView/index.tsx
  src/features/profile/components/ProfileShare/ShareButtons.tsx
  src/features/profile/components/ProfileView/index.tsx
  src/features/user-management/components/UserTable.tsx
  src/features/user-management/types/user.ts
  src/shared/components/Analytics.tsx
  src/shared/components/GoogleAnalytics.tsx
  src/shared/hooks/index.ts
  src/shared/hooks/useAnalytics.ts
  src/shared/hooks/useTableGrid.ts
  src/shared/hooks/useTableSelection.ts
  src/shared/ui/Icons/CustomIcons.tsx
  src/shared/ui/Icons/Icon.tsx
  src/shared/ui/Icons/Icons.types.ts
  src/shared/ui/Table/AdminTable.tsx
  src/shared/ui/Table/EnhancedTable.tsx
  src/shared/ui/Table/Table.stories.tsx
  src/shared/ui/Table/Table.tsx
  src/shared/ui/Table/Table.types.ts
  src/shared/ui/Table/TableActions/TableActions.tsx
  src/shared/ui/Table/TableActions/index.ts
  src/shared/ui/Table/TableCheckbox/TableCheckbox.tsx
  src/shared/ui/Table/TableCheckbox/index.ts
  src/shared/ui/Table/TableSkeleton/TableSkeleton.tsx
  src/shared/ui/Table/TableSkeleton/index.ts
  src/shared/ui/Table/index.ts
  src/shared/ui/Table/index.tsx
  src/shared/ui/Title/Title.tsx
  src/shared/ui/Title/index.ts
  src/types/analytics.ts
  src/types/global.d.ts
  src/utils/analytics.ts
Labels: enhancement

#269 UF-260 업적 페이지 제작
  public/icons/badges/locked.svg
  public/icons/badges/lv1-1.svg
  public/icons/badges/lv1-2.svg
  public/icons/badges/lv1-3.svg
  public/icons/badges/lv2-1.svg
  public/icons/badges/lv2-2.svg
  public/icons/badges/lv2-3.svg
  public/icons/badges/lv3-1.svg
  public/icons/badges/lv3-2.svg
  public/icons/badges/lv3-3.svg
  public/icons/badges/lv4-1.svg
  public/icons/badges/lv4-2.svg
  public/icons/badges/lv4-3.svg
  public/images/alien-pointing.svg
  public/images/cloud.svg
  src/app/mypage/achievement/page.tsx
  src/constants/images.ts
  src/features/mypage/components/AchievementBadge.tsx
  src/styles/components/typography.css
  src/styles/globals.css
Labels: enhancement

#270 UF-253 토스트 메세지 위치 변경 및 구조 개선
  src/app/layout.tsx
  src/constants/index.ts
  src/constants/toast.ts
  src/shared/ui/Sonner/Sonner.tsx
Labels: enhancement

#281 UF-269 CI 환경에서 husky 설치 방지를 통한 Vercel 배포 오류 해결
  package-lock.json
  package.json
Labels: bug

#282 UF-269 is-ci가 devDependencies에 있어서 설치되지 않는 문제 해결
  package.json
Labels: bug

#283 UF-269 프로덕션 빌드를 위해 raw-loader를 dependencies로 이동
  package-lock.json
  package.json
Labels: bug

#287 UF-274 build 스크립트에 prisma generate 추가
  package-lock.json
  package.json
Labels: bug

#289 UF-275 develop 브랜치에서도 개인 레포 자동 배포 설정 추가
  .github/workflows/build-and-deploy.yml
Labels: bug

#294 UF-275 deploy-vercel 제거
  .github/workflows/build-and-deploy.yml
Labels: bug

#300 UF-277 assets 리소스를 constants 폴더로 이동
  src/app/mypage/privacy/page.tsx
  src/app/mypage/service/page.tsx
  src/assets/mascot.png
  src/constants/terms/privacy.md
  src/constants/terms/service.md
  src/constants/terms/termsRenderer.tsx
Labels: enhancement

#304 UF-265 새로운 ZET 이미지로 교체
  public/images/package-A.png
  public/images/package-B.png
  public/images/package-C.png
  public/images/package-D.png
  public/images/package-E.png
  public/images/zet-1.png
  public/images/zet-2.png
  public/images/zet-3.png
  public/images/zet-4.png
  public/images/zet-5.png
  src/constants/images.ts
Labels: enhancement

#290 UF-270 에러 핸들러 및 axiosInstance로 적혀있는 API 수정
  src/api/services/history/purchaseHistory.ts
  src/api/services/history/sellHistory.ts
  src/api/services/notification/settings.ts
  src/api/types/exchange.ts
  src/app/api/cron/cleanup/route.ts
  src/app/login/page.tsx
  src/app/login/success/page.tsx
  src/app/mypage/notification/page.tsx
  src/app/mypage/trade/page.tsx
  src/app/test/page.tsx
  src/features/bulk/components/BulkResultContent.tsx
  src/stores/useToastStore.ts
Labels: enhancement

#301 UF-271 다른 사용자 프로필 조회 엔드포인트 수정
  src/api/services/profile/profile.ts
  src/api/types/api.ts
  src/app/profile/[userId]/layout.tsx
Labels: enhancement

#306 UF-282 배경 이미지 반복 및 불필요한 스크롤 문제 수정
  .coderabbit.yaml
  src/app/exchange/bulk/result/index.tsx
  src/app/exchange/bulk/result/page.tsx
  src/app/layout.tsx
  src/app/login/success/page.tsx
  src/app/mypage/achievement/page.tsx
  src/app/mypage/edit-profile/page.tsx
  src/app/mypage/follow/layout.tsx
  src/app/mypage/follow/page.tsx
  src/app/payment/fail/page.tsx
  src/app/payment/success/page.tsx
  src/app/profile/[userId]/datalist/page.tsx
  src/app/profile/[userId]/page.tsx
  src/app/sell/edit/[id]/page.tsx
  src/app/sell/page.tsx
  src/app/signup/plan/page.tsx
  src/app/signup/profile/page.tsx
  src/features/bulk/components/BulkResultContent.tsx
  src/features/exchange/components/EditProvider.tsx
  src/features/hooks/useSellData.ts
  src/features/mypage/follow/components/FollowItem.tsx
  src/features/mypage/follow/components/FollowTabContent.tsx
  src/features/profile/components/DataListView/index.tsx
  src/features/profile/components/ProfileView/index.tsx
  src/provider/AppLayoutProvider.tsx
  src/provider/BackgroundProvider.tsx
  src/provider/index.ts
Labels: bug, enhancement

#311 UF-275 schema 경로 명시
  package.json
Labels: bug

#313 UF-275 schema 루트 디렉토리 명시
  package.json
Labels: bug

#314 UF-275 prisma 복사 추가
  .github/workflows/build-and-deploy.yml
  package.json
Labels: bug

#317 UF-275 build.sh 추가
  .github/workflows/build-and-deploy.yml
  build.sh
Labels: bug

#319 UF-275 .git 파일 제외
  build.sh
Labels: bug

#284 UF-267 cleanup admin page code
  src/api/types/bannedWords.ts
  src/app/admin/banned-words/page.tsx
  src/app/admin/posts/reported/page.tsx
  src/app/admin/user/inactive/page.tsx
  src/features/admin/hooks/useBannedWords.ts
Labels: enhancement

#327 UF-288 OCR 컴포넌트화 및 build.sh 수정
  build.sh
  src/app/mypage/edit-profile/page.tsx
  src/app/signup/plan/page.tsx
  src/features/mypage/components/PlanEditor.tsx
  src/features/mypage/hooks/useEditProfile.tsx
  src/features/signup/components/OcrInputSection/OcrInputSection.tsx
  src/features/signup/components/OcrInputSection/OcrInputSection.types.ts
  src/features/signup/components/OcrInputSection/index.ts
  src/features/signup/components/OcrInputSection/ocrInputVariants.ts
  src/features/signup/components/PlanCombo/PlanCombo.tsx
  src/features/signup/components/PlanCombo/PlanCombo.types.ts
  src/features/signup/components/index.ts
Labels: enhancement

#315 UF-286 add loading components
  src/app/loading.tsx
  src/shared/ui/Loading/Loading.stories.tsx
  src/shared/ui/Loading/Loading.tsx
  src/shared/ui/Loading/Loading.types.ts
  src/shared/ui/Loading/Loading.variants.ts
  src/shared/ui/Loading/index.ts
  src/shared/ui/index.ts
Labels: enhancement

#333 UF-295 마이페이지 UI/UX 개선 - 업적 시스템 연결 및 고객 지원 메뉴 확장
  src/app/mypage/page.tsx
Labels: enhancement

#334 UF-296 충전 페이지 패키지 카드 반응형 UI 개선
  src/features/charge/components/ZetChargePackageCard.tsx
Labels: enhancement

#332 UF-300 편지 제작 로직 수정
  prisma/schema.prisma
  src/app/api/story/letters/[userId]/route.ts
  src/app/api/story/letters/route.ts
  src/app/test/letters/page.tsx
Labels: enhancement

#331 UF-294 데이터 판매 등록 UI 수정
  package-lock.json
  src/app/sell/edit/[id]/page.tsx
  src/app/sell/page.tsx
  src/features/hooks/useSellData.ts
  src/features/sell/components/SellCapacitySlider.tsx
  src/lib/validate.ts
  src/shared/components/Analytics.tsx
  src/shared/ui/Input/PriceInput.tsx
Labels: enhancement

#351 UF-313 네비게이션 바가 메인 콘텐츠를 가리는 레이아웃 버그 수정
  src/provider/AppLayoutProvider.tsx
  src/shared/layout/BottomNav/BottomNav.tsx
  src/shared/layout/TopNav/TopNav.tsx
Labels: bug

#349 UF-303 구매내역 상세 페이지 추가
  public/images/myplanet-half.svg
  public/images/receipt.svg
  src/api/services/mypage/purchaseDetail.ts
  src/app/mypage/trade/detail/page.tsx
  src/app/mypage/trade/page.tsx
  src/constants/images.ts
  src/features/mypage/components/TradeHistoryCard.tsx
  src/features/mypage/components/index.ts
  src/features/mypage/components/trade-detail/CompletionImage.tsx
  src/features/mypage/components/trade-detail/EmptyState.tsx
  src/features/mypage/components/trade-detail/ErrorState.tsx
  src/features/mypage/components/trade-detail/ReceiptContent.tsx
  src/features/mypage/components/trade-detail/index.ts
  src/features/mypage/hooks/index.ts
  src/features/mypage/hooks/usePurchaseDetail.ts
  src/features/mypage/types/TradeHistoryCard.types.ts
  src/features/mypage/utils/tradeDetail.ts
  src/provider/AppLayoutProvider.tsx
  src/provider/AuthProvider.tsx
Labels: enhancement

#348 UF-307 모바일 데이터 타입 관련 필드 타입을 모두 MobileDataType으로 통일
  src/api/types/exchange.ts
  src/api/types/history.ts
  src/api/types/mobileData.ts
  src/api/types/plan.ts
  src/api/types/profile.ts
  src/features/bulk/types/bulkResult.types.ts
  src/features/exchange/components/ExchangeList.tsx
  src/features/mypage/hooks/useEditProfile.tsx
  src/features/profile/components/DataListView/SimpleDataCard.tsx
  src/features/profile/components/ProfileView/ProfileContentSections.tsx
  src/features/profile/stories/ProfileView.stories.tsx
  src/features/signup/components/OcrInputSection/OcrInputSection.tsx
  src/utils/index.ts
  src/utils/mobileData.ts
Labels: enhancement

#355 UF-306 알림설정 페이지 Redesign
  src/app/mypage/notification/page.tsx
Labels: enhancement

#358 UF-318 앱 레이아웃 프로바이더 버그 수정
  src/app/page.tsx
  src/features/main/components/OrbitWithSatellite.tsx
  src/features/main/components/PlanetProgressBar.tsx
  src/provider/AppLayoutProvider.tsx
  src/provider/AuthProvider.tsx
Labels: bug

#361 UF-316 블랙홀 페이지 수정
  src/app/blackhole/layout.tsx
  src/app/blackhole/page.tsx
  src/provider/AppLayoutProvider.tsx
Labels: bug, enhancement

#362 UF-309 update charge page for myzet
  src/api/types/myInfo.ts
  src/app/charge/layout.tsx
  src/app/charge/page.tsx
  src/app/login/page.tsx
  src/app/mypage/page.tsx
  src/constants/images.ts
  src/features/mypage/components/SignalCard.tsx
  src/features/mypage/hooks/useMyInfo.ts
Labels: enhancement

#369 UF-310 전파거리-전파궤도 ui 1차안
  public/images/satellite1.svg
  public/images/satellite2.svg
  public/images/satellite3.svg
  public/images/satellite4.svg
  public/images/satellite5.svg
  src/app/signal/page.tsx
  src/constants/images.ts
  src/features/signal/components/PlanetComponent.tsx
  src/features/signal/components/SignalTabContent.tsx
Labels: enhancement

#374 UF-328 전파 거래소 우측 하단에 맨 위 이동 버튼 추가
  src/app/exchange/page.tsx
  src/features/common/components/ScrollToTopButton.tsx
  src/hooks/useScrollToTop.ts
  src/hooks/useScrollTracker.ts
  src/shared/ui/Icons/Icons.types.ts
  src/stores/useScrollStore.ts
Labels: enhancement

#372 UF-325 충전 및 결제 정보 API 스펙 수정 및 중복 요청 방지
  src/api/types/payment.ts
  src/app/charge/page.tsx
  src/app/payment/fail/page.tsx
  src/app/payment/success/page.tsx
  src/features/charge/components/ZetChargePackageCard.tsx
  src/features/charge/hooks/useTossPayments.ts
  src/features/charge/hooks/useZetCharge.ts
  src/shared/ui/Button/buttonVariants.ts
Labels: enhancement

#376 UF-322 UserLink 컴포넌트를 활용한 닉네임 클릭 시 프로필 조회 기능 구현
  src/app/profile/[userId]/layout.tsx
  src/features/exchange/components/SellingItem.tsx
  src/features/mypage/follow/components/FollowItem.tsx
  src/features/mypage/hooks/useMyInfo.ts
  src/features/profile/components/ProfileView/ProfileContentSections.tsx
  src/features/profile/components/ProfileView/ProfileHeader.tsx
  src/features/profile/components/ProfileView/index.tsx
  src/features/profile/hooks/useFollowStatus.ts
  src/features/profile/hooks/useProfileFollowActions.ts
  src/features/profile/hooks/useProfileWithFollow.ts
  src/features/profile/stories/ProfileView.stories.tsx
  src/shared/ui/UserLink/index.tsx
  src/utils/queryClient.ts
Labels: enhancement

#378 UF-331 정적 이미지 아이콘의 불필요한 로딩 상태 제거
  src/shared/ui/Icons/ImageIcon.tsx
Labels: enhancement

#346 UF-308 업적 API 연동 및 세부 페이지 작성
  prisma/schema.prisma
  src/api/client/axios.ts
  src/api/services/mypage/achievement.ts
  src/app/api/achievements/update/route.ts
  src/app/api/collections/route.ts
  src/app/api/collections/search/route.ts
  src/app/api/story/letters/route.ts
  src/app/mypage/achievement/page.tsx
  src/features/mypage/components/AchievementBadge.tsx
  src/shared/ui/Modal/AchievementModal.tsx
  src/shared/ui/Modal/Modal.types.ts
  src/shared/ui/Modal/index.ts
  src/types/Achievement.ts
  src/utils/getAchievedDate.ts
Labels: enhancement

#382 UF-330 변경된 API에 맞춰 내역 response 수정
  src/api/types/history.ts
  src/app/mypage/trade/page.tsx
Labels: enhancement

#390 UF-336 리프레시 토큰 쿠키 기반으로 수정 및 요청 큐 처리 개선
  src/api/client/axios.ts
Labels: bug

#394 UF-339 타 사용자 프로필에 업적 및 거래 현황 추가 ***** UF-333 보다 먼지 MERGE 해야 함 *****
  prisma/schema.prisma
  src/api/types/profile.ts
  src/app/api/achievements/update/route.ts
  src/app/api/collections/route.ts
  src/app/api/collections/search/route.ts
  src/app/api/collections/user-stats/route.ts
  src/app/mypage/achievement/page.tsx
  src/app/test/page.tsx
  src/constants/images.ts
  src/features/profile/components/ProfileView/ProfileContentSections.tsx
  src/lib/vectorizer.ts
  src/types/Achievement.ts
Labels: enhancement

#396 UF-340 login, signup에서는 사용자 정보를 가져오지 않도록 수정
  src/provider/AuthProvider.tsx
Labels: bug, enhancement

#367 UF-315 일괄구매 API 및 완료 페이지
  src/api/services/auth/logout.ts
  src/api/services/exchange/bulkPurchase.ts
  src/app/exchange/bulk/purchase/page.tsx
  src/app/exchange/bulk/result/page.tsx
  src/features/bulk/components/BulkPurchaseContent.tsx
  src/features/bulk/components/BulkResultCard.tsx
  src/features/bulk/components/BulkResultContent.tsx
  src/features/bulk/hooks/useBulkPurchase.ts
  src/features/bulk/types/bulkResult.types.ts
  src/stores/useBulkStore.ts
Labels: enhancement

#402 UF-343 QA 1차 수정 0731-v1
  src/app/exchange/notification/page.tsx
  src/app/exchange/purchase/[id]/step2/page.tsx
  src/features/exchange/components/FilterBox.tsx
  src/features/mypage/components/SignalCard.tsx
  src/provider/AppLayoutProvider.tsx
  src/provider/AuthProvider.tsx
  src/shared/ui/Header/Header.tsx
Labels: bug, enhancement

#406 UF-345 QA 2차 수정 0731-v2
  src/app/exchange/page.tsx
  src/features/common/components/ScrollToTopButton.tsx
  src/features/common/components/ZetDisplay/ZetDisplay.tsx
  src/features/common/components/ZetDisplay/index.ts
  src/features/exchange/components/ExchangeList.tsx
  src/features/mypage/components/SignalCard.tsx
  src/hooks/useScrollToTop.ts
  src/provider/AppLayoutProvider.tsx
  src/shared/layout/TopNav/TopNav.tsx
Labels: enhancement

#409 UF-346 회원가입 되도록 임시 조치
  src/app/signup/layout.tsx
  src/app/signup/plan/page.tsx
Labels: enhancement
