Repository Ureca-Final-Project-Team1/UFO-Fi-FE, pull requests merged in 2025-08, with the labels that each got.

#430 UF-356 내역 페이지 링크 쿼리파라미터로 변경
  src/app/mypage/page.tsx
  src/app/mypage/trade/page.tsx
  src/stores/useTradeTabStore.ts
Labels: enhancement

#411 UF-344 칭호 제작 및 마이페이지 적용
  prisma/schema.prisma
  src/api/services/mypage/achievement.ts
  src/app/api/achievements/honor/route.ts
  src/app/api/achievements/honor/select/route.ts
  src/app/mypage/page.tsx
  src/features/mypage/components/HonorificChip.tsx
  src/features/mypage/components/HonorificSelector.tsx
  src/features/mypage/components/SignalCard.tsx
  src/shared/ui/Chip/Chip.tsx
  src/shared/ui/Chip/Chip.types.ts
  src/types/Achievement.ts
Labels: enhancement

#437 UF-349 AdminSideMenu 리팩토링
  src/shared/ui/AdminSideMenu/AdminSideMenu.tsx
Labels: enhancement

#440 UF-351 Title 리팩토링
  src/shared/ui/Title/Title.tsx
Labels: enhancement

#454 UF-372 Next API 에러 핸들러 구체화
  src/api/services/follow/recommend.ts
  src/api/types/follow.ts
  src/app/api/achievements/honor/route.ts
  src/app/api/achievements/honor/select/route.ts
  src/app/api/achievements/update/route.ts
  src/app/api/chat/route.ts
  src/app/api/collections/route.ts
  src/app/api/collections/search/route.ts
  src/app/api/collections/user-stats/route.ts
  src/app/api/cron/cleanup/route.ts
  src/app/api/ocr/route.ts
  src/app/test/page.tsx
Labels: enhancement

#452 UF-370 AppLayoutProvider 메인 영역을 네비게이션이 잡아먹는 버그 수정
  src/app/blackhole/layout.tsx
  src/app/blackhole/page.tsx
  src/app/charge/layout.tsx
  src/app/charge/page.tsx
  src/app/exchange/bulk/layout.tsx
  src/app/exchange/bulk/page.tsx
  src/app/exchange/bulk/result/index.tsx
  src/app/exchange/bulk/result/layout.tsx
  src/app/exchange/layout.tsx
  src/app/exchange/notification/page.tsx
  src/app/exchange/page.tsx
  src/app/exchange/purchase/[id]/page.tsx
  src/app/exchange/purchase/[id]/step1/page.tsx
  src/app/exchange/purchase/[id]/step2/page.tsx
  src/app/exchange/purchase/[id]/step3/page.tsx
  src/app/login/page.tsx
  src/app/login/success/page.tsx
  src/app/mypage/achievement/page.tsx
  src/app/mypage/edit-profile/page.tsx
  src/app/mypage/follow/layout.tsx
  src/app/mypage/follow/page.tsx
  src/app/mypage/notification/page.tsx
  src/app/mypage/page.tsx
  src/app/mypage/privacy/layout.tsx
  src/app/mypage/service/layout.tsx
  src/app/mypage/trade/page.tsx
  src/app/onboarding/page.tsx
  src/app/payment/account/page.tsx
  src/app/payment/account/success/layout.tsx
  src/app/payment/fail/layout.tsx
  src/app/payment/fail/page.tsx
  src/app/payment/success/layout.tsx
  src/app/profile/[userId]/datalist/page.tsx
  src/app/profile/[userId]/layout.tsx
  src/app/profile/[userId]/loading.tsx
  src/app/profile/[userId]/page.tsx
  src/app/sell/edit/[id]/layout.tsx
  src/app/sell/edit/[id]/page.tsx
  src/app/sell/layout.tsx
  src/app/sell/page.tsx
  src/app/signal/page.tsx
  src/app/signup/layout.tsx
  src/features/bulk/components/BulkPurchaseContent.tsx
  src/features/bulk/components/BulkResultContent.tsx
  src/features/exchange/components/EditProvider.tsx
  src/features/exchange/components/FilterBox.tsx
  src/features/exchange/components/SellingItem.tsx
  src/features/profile/components/DataListView/index.tsx
  src/features/profile/components/ProfileView/index.tsx
  src/features/profile/stories/ProfileView.stories.tsx
  src/features/signal/components/LetterTabContent.tsx
  src/provider/AppLayoutProvider.tsx
  src/provider/ToastProvider.tsx
  src/shared/layout/BottomNav/BottomNav.tsx
  src/shared/layout/TopNav/TopNav.tsx
  src/shared/ui/Loading/Loading.tsx
  src/styles/components/navigation.css
  src/styles/components/toast.css
  src/styles/globals.css
Labels: bug, enhancement

#457 UF-364 BankSelectSheet 리팩토링
  src/features/payments/components/BankSelectSheet.styles.ts
  src/features/payments/components/BankSelectSheet.tsx
Labels: enhancement

#441 UF-352 TitleWithoutRouter 리팩토링
  src/shared/ui/Title/TitleWithoutRouter.tsx
Labels: enhancement

#451 UF-361 IconWrapper 리팩토링
  src/shared/ui/Icons/CustomIcons.tsx
  src/shared/ui/Icons/Icon.tsx
  src/shared/ui/Icons/IconWrapper.tsx
  src/shared/ui/Icons/IconWrapperVariants.ts
Labels: enhancement

#446 UF-358 Indicator 리팩토링
  src/shared/ui/Indicator/Indicator.tsx
  src/shared/ui/Indicator/Indicator.types.ts
  src/shared/ui/Indicator/IndicatorVariants.ts
  src/shared/ui/Indicator/index.ts
  src/shared/ui/Indicator/indicatorVariants.ts
Labels: enhancement

#444 UF-355 NotificationTrigger 리팩토링
  src/shared/ui/NotificationDropdown/NotificationTrigger.tsx
  src/shared/ui/NotificationDropdown/NotificationTriggerVariants.ts
Labels: enhancement

#445 UF-357 ReportModal 리펙토링
  src/shared/ui/Modal/ReportModal.tsx
  src/shared/ui/Modal/ReportModalVariants.ts
Labels: enhancement

#456 UF-363 NotificationItem 리팩토링
  src/shared/ui/NotificationDropdown/NotificationItem.tsx
  src/shared/ui/NotificationDropdown/NotificationItemVariants.ts
Labels: enhancement

#466 UF-374 QA 3차 리팩토링 및 버그 수정
  next.config.ts
  package.json
  src/app/charge/layout.tsx
  src/app/exchange/bulk/page.tsx
  src/app/exchange/bulk/result/index.tsx
  src/app/exchange/bulk/result/layout.tsx
  src/app/exchange/page.tsx
  src/app/exchange/purchase/[id]/step1/page.tsx
  src/app/exchange/purchase/[id]/step2/page.tsx
  src/app/exchange/purchase/[id]/step3/page.tsx
  src/app/mypage/achievement/page.tsx
  src/app/mypage/follow/page.tsx
  src/app/mypage/privacy/page.tsx
  src/app/mypage/service/layout.tsx
  src/app/mypage/service/page.tsx
  src/app/not-found.tsx
  src/app/payment/account/page.tsx
  src/app/payment/account/success/layout.tsx
  src/app/payment/account/success/page.tsx
  src/app/payment/fail/page.tsx
  src/app/payment/password/page.tsx
  src/app/payment/success/page.tsx
  src/app/sell/edit/[id]/layout.tsx
  src/app/sell/edit/[id]/page.tsx
  src/app/signal/page.tsx
  src/constants/terms/privacy.ts
  src/constants/terms/service.ts
  src/features/bulk/components/BulkResultContent.tsx
  src/features/common/components/MarkdownRenderer/MarkdownRenderer.tsx
  src/features/exchange/components/ExchangeFilters.tsx
  src/features/mypage/components/SignalCard.tsx
  src/features/profile/components/DataListView/SimpleDataCard.tsx
  src/features/profile/hooks/useProfileShare.ts
  src/features/profile/utils/shareUtils.ts
  src/hooks/useScrollTracker.ts
  src/provider/ToastProvider.tsx
  src/shared/ui/Sonner/Sonner.stories.tsx
  src/shared/ui/Title/Title.tsx
  src/styles/components/toast.css
  src/types/markdown.d.ts
  src/utils/queryClient.ts
Labels: bug, enhancement

#449 UF-359 ImageIcon 리팩토링
  src/shared/ui/Icons/Icon.tsx
  src/shared/ui/Icons/ImageIcon.tsx
  src/shared/ui/Icons/ImageIconVariants.ts
Labels: enhancement

#471 Uf-380 QA 4차 수정 및 디벨롭 버그 수정
  src/app/admin/page.tsx
  src/app/admin/posts/page.tsx
  src/app/admin/settings/page.tsx
  src/app/admin/user/page.tsx
  src/app/blackhole/layout.tsx
  src/app/blackhole/page.tsx
  src/app/exchange/bulk/result/index.tsx
  src/app/loading.tsx
  src/app/login/page.tsx
  src/app/signup/layout.tsx
  src/app/signup/plan/page.tsx
  src/features/admin/components/AdminSideMenu/AdminSideMenu.stories.tsx
  src/features/admin/components/AdminSideMenu/AdminSideMenu.tsx
  src/features/admin/components/AdminSideMenu/index.ts
  src/features/admin/components/UserCommand/UserCommand.tsx
  src/features/admin/components/UserTable/UserTable.tsx
  src/features/admin/types/user.ts
  src/features/signup/components/OcrInputSection/OcrInputSection.tsx
  src/features/user-management/components/UserManagementPage.tsx
  src/shared/ui/Icons/Icon.tsx
  src/shared/ui/Loading/Loading.tsx
  src/shared/ui/Loading/Loading.types.ts
  src/shared/ui/Loading/Loading.variants.ts
  src/shared/ui/Sidebar/Sidebar.tsx
  src/shared/ui/index.ts
Labels: bug, enhancement

#474 UF-384 알림 드롭다운, 헤더 알림 버튼 디자인 수정
  src/shared/layout/TopNav/TopNav.tsx
  src/shared/ui/Icons/CustomIcons.tsx
  src/shared/ui/Icons/Icon.tsx
  src/shared/ui/Icons/IconVariants.ts
  src/shared/ui/Icons/IconWrapper.tsx
  src/shared/ui/Icons/IconWrapperVariants.ts
  src/shared/ui/Icons/Icons.types.ts
  src/shared/ui/Icons/ImageIcon.tsx
  src/shared/ui/Icons/ImageIconVariants.ts
  src/shared/ui/Icons/LucideIcon.tsx
  src/shared/ui/NotificationDropdown/NotificationDropdown.tsx
  src/shared/ui/NotificationDropdown/NotificationDropdownVariants.ts
  src/shared/ui/NotificationDropdown/NotificationItem.tsx
  src/shared/ui/NotificationDropdown/NotificationItemVariants.ts
  src/shared/ui/NotificationDropdown/NotificationTrigger.tsx
  src/shared/ui/NotificationDropdown/NotificationTriggerVariants.ts
Labels: bug, enhancement

#475 UF-380 게시물 상세 조회 API 도입 및 수정 pathname 변경
  src/api/services/sell/posts.ts
  src/api/types/sell.ts
  src/app/exchange/page.tsx
  src/features/exchange/components/EditProvider.tsx
  src/features/exchange/components/ExchangeFilters.tsx
  src/features/exchange/components/ExchangeHeader.tsx
  src/features/exchange/components/ExchangeList.tsx
  src/features/exchange/components/ExchangeListSkeleton.tsx
  src/features/exchange/components/SellingItem.tsx
  src/features/exchange/hooks/useInfiniteExchangePosts.ts
  src/features/exchange/hooks/useOptimizedInfiniteScroll.ts
Labels: enhancement

#478 UF-376 온보딩 페이지 1차안
  public/images/onboarding/window-border.svg
  public/images/onboarding/window-bottom.svg
  public/images/onboarding/window-mask.svg
  public/images/onboarding/window.svg
  src/app/onboarding/layout.tsx
  src/app/onboarding/page.tsx
  src/constants/images.ts
  src/features/onboarding/components/AlienCharacter.tsx
  src/features/onboarding/components/AlienWithSpeech.tsx
  src/features/onboarding/components/OnboardingImageFrame.tsx
  src/features/onboarding/components/StepIndicator.tsx
  src/provider/AppLayoutProvider.tsx
  src/styles/globals.css
Labels: enhancement

#489 UF-382 login metadata 리팩토링
  src/app/layout.tsx
  src/app/login/layout.tsx
  src/app/login/page.tsx
  src/provider/AppLayoutProvider.tsx
  src/styles/components/background.css
  src/utils/metadata.ts
Labels: enhancement

#487 UF-391 Notification_Histories API 연결
  prisma/schema.prisma
  src/app/api/notifications/[id]/read/route.ts
  src/app/api/notifications/route.ts
Labels: enhancement

#496 UF-392 SellingItem 컴포넌트 디자인, 레이아웃 변경
  src/features/exchange/components/SellingItem.tsx
Labels: enhancement

#493 UF-393 판매 수정 및 등록 페이지 버그 수정
  src/app/sell/edit/[id]/page.tsx
  src/app/sell/page.tsx
  src/backend/index.ts
  src/backend/services/mypage/userPlan.ts
  src/backend/types/userPlan.ts
  src/constants/images.ts
  src/features/payment/components/NumberButton.tsx
  src/features/payment/components/PasswordInput.tsx
  src/features/payment/components/PasswordPad.tsx
  src/features/payment/components/SimplePasswordModal.stories.tsx
  src/features/payment/components/SimplePasswordModal.tsx
  src/features/payment/types/PasswordPad.types.ts
  src/features/payments/components/BankSelectSheet.styles.ts
  src/features/payments/components/BankSelectSheet.tsx
  src/features/payments/constants/BankAccountFormats.ts
  src/features/payments/constants/BankOptions.ts
  src/features/payments/utils/accountFormat.ts
  src/shared/ui/Input/AccountInput.tsx
  src/shared/ui/Input/BankSelectInput.tsx
  src/shared/ui/Input/index.ts
  src/shared/ui/Input/input.stories.tsx
Labels: bug

#503 UF-396 온보딩 페이지 UI 레이아웃 확정, 시멘틱, 코드 리팩토링 완료
  public/images/alien-onboarding.png
  public/images/alien-onboarding.svg
  src/app/onboarding/page.tsx
  src/constants/images.ts
  src/features/onboarding/components/AlienCharacter.tsx
  src/features/onboarding/components/AlienWithSpeech.tsx
  src/features/onboarding/components/NextButton.tsx
  src/features/onboarding/components/OnboardingImageFrame.tsx
  src/features/onboarding/components/StepIndicator.tsx
  src/features/onboarding/utils/onboarding.ts
Labels: enhancement

#500 UF-394 백오피스 제트 복구 페이지 ui 구현
  src/app/admin/zet-recovery/page.tsx
  src/features/admin/components/AdminSideMenu/AdminSideMenu.tsx
  src/shared/ui/Icons/Icons.types.ts
  src/shared/ui/Sidebar/Sidebar.tsx
Labels: enhancement

#505 UF-398 오픈그래프 이미지 추가
  public/images/open-graph.png
  src/app/layout.tsx
  src/constants/index.ts
  src/constants/metadata.ts
Labels: enhancement

#509 UF-401 Sell 및 Bulk 페이지 css 수정 및 UserLink Link 컴포넌트 사용
  src/app/exchange/bulk/page.tsx
  src/app/mypage/follow/page.tsx
  src/app/sell/page.tsx
  src/features/bulk/components/BulkPurchaseContent.tsx
  src/features/sell/components/SellTotalPrice.tsx
  src/shared/ui/UserLink/index.tsx
Labels: enhancement

#520 UF-406 Next 서버와 api 통신
  src/app/api/achievements/honor/route.ts
  src/app/api/achievements/honor/select/route.ts
  src/app/api/achievements/update/route.ts
  src/app/api/collections/route.ts
  src/app/api/collections/search/route.ts
  src/app/api/collections/user-stats/route.ts
  src/app/api/notifications/[id]/read/route.ts
  src/app/api/notifications/route.ts
  src/app/api/story/letters/route.ts
  src/backend/client/axios.ts
  src/constants/api.ts
Labels: enhancement

#511 UF-399 Signup CSS 수정 및 planCombo 버그 수정
  src/app/signup/layout.tsx
  src/app/signup/plan/layout.tsx
  src/app/signup/plan/page.tsx
  src/app/signup/privacy/layout.tsx
  src/app/signup/privacy/page.tsx
  src/app/signup/profile/layout.tsx
  src/app/signup/profile/page.tsx
  src/features/signup/components/PlanCombo/PlanCombo.tsx
  src/features/signup/components/SignupClientLayout.tsx
Labels: enhancement

#513 UF-402 타 사용자 프로필 sellingItem 사용 및 메인화면 onClick 제거
  src/backend/types/profile.ts
  src/constants/images.ts
  src/features/hooks/useSellData.ts
  src/features/main/components/OrbitWithSatellite.tsx
  src/features/profile/components/DataListView/index.tsx
  src/features/profile/stories/ProfileView.stories.tsx
Labels: enhancement

#522 UF-411 레이아웃 & 토스트 위치 수정
  src/app/layout.tsx
  src/app/page.tsx
  src/app/providers.tsx
  src/provider/AppLayoutProvider.tsx
  src/provider/ToastProvider.tsx
  src/shared/layout/BottomNav/BottomNav.tsx
  src/styles/globals.css
Labels: bug, enhancement

#523 UF-414 mypage 팔로워 추천 Carousel 추가
  src/app/mypage/page.tsx
  src/app/payment/fail/page.tsx
  src/app/payment/success/page.tsx
  src/app/signal/page.tsx
  src/backend/services/follow/recommend.ts
  src/backend/types/follow.ts
  src/features/bulk/components/BulkPurchaseContent.tsx
  src/features/mypage/components/FollowCarousel.tsx
  src/features/mypage/components/FollowCarouselSkeleton.tsx
  src/features/mypage/components/MenuSection.tsx
  src/features/profile/components/Carousel/EmblaCarousel.tsx
Labels: enhancement

#533 UF-419 거래소 Refetch 및 profile/datalist layout 추가
  src/app/exchange/page.tsx
  src/app/profile/[userId]/datalist/layout.tsx
  src/features/exchange/components/ExchangeList.tsx
  src/shared/ui/Modal/ReportModal.tsx
  src/shared/ui/UserLink/index.tsx
Labels: bug, enhancement

#535 UF-424 각종 버그 수정 및 로직 수정
  src/app/mypage/edit-profile/page.tsx
  src/backend/services/profile/profile.ts
  src/features/mypage/components/FollowCarousel.tsx
  src/features/mypage/hooks/useEditProfile.tsx
  src/features/profile/components/ProfileView/ProfileContentSections.tsx
  src/features/signup/components/OcrInputSection/OcrInputSection.tsx
Labels: bug, enhancement

#537 UF-426 같은 통신사만 구매 가능하도록 수정
  src/app/exchange/page.tsx
  src/app/sell/page.tsx
  src/features/exchange/components/ExchangeList.tsx
  src/features/exchange/components/SellingItem.tsx
  src/features/profile/components/DataListView/index.tsx
  src/shared/hooks/useUserPlan.ts
Labels: bug, enhancement

#540 UF-428 판매 가능 용량 및 ZET Refetch
  src/app/api/collections/route.ts
  src/app/exchange/purchase/[id]/step1/page.tsx
  src/app/exchange/purchase/[id]/step3/page.tsx
  src/features/hooks/useSellData.ts
Labels: bug, enhancement

#559 UF-397 엔드포인트 수정
  src/backend/services/auth/userInfo.ts
Labels: bug

#560 UF-449 페이지 ui 오류 수정
  src/app/login/page.tsx
Labels: bug, enhancement

#572 UF-455 QA 버그 수정: 루트 /login로 변경 및 회원가입 온보딩 시 네비게이션 비활성화
  src/middleware.ts
  src/provider/AppLayoutProvider.tsx
  src/shared/layout/BottomNav/BottomNav.tsx
  src/shared/layout/TopNav/TopNav.tsx
Labels: bug

#570 UF-456 프로필 페이지 수정
  src/features/profile/components/DataListView/index.tsx
Labels: bug, enhancement

#574 UF-457 전파 거래소 페이지 필터링 조회 기능 추가
  src/app/exchange/page.tsx
  src/app/mypage/page.tsx
  src/features/exchange/components/ExchangeFilters.tsx
  src/features/exchange/components/ExchangeHeader.tsx
  src/features/exchange/components/ExchangeList.tsx
  src/shared/ui/Chip/Chip.tsx
Labels: enhancement

#576 UF-461 어드민 페이지 에러 해결 및 프로필 수정 페이지
  src/app/admin/banned-words/page.tsx
  src/app/login/success/page.tsx
  src/app/mypage/edit-profile/page.tsx
  src/app/signup/plan/page.tsx
  src/backend/services/admin/bannedWords.ts
  src/backend/services/admin/zetRecovery.ts
  src/backend/services/report/report.ts
  src/constants/api.ts
  src/features/admin/hooks/useBannedWords.ts
  src/features/mypage/components/NicknameEditor.tsx
  src/features/mypage/components/PlanEditor.tsx
  src/features/signup/components/OcrInputSection/OcrInputSection.tsx
  src/features/signup/components/OcrInputSection/OcrInputSection.types.ts
  src/features/signup/components/PlanCombo/PlanCombo.tsx
  src/features/signup/components/PlanCombo/PlanCombo.types.ts
Labels: bug, enhancement

#579 UF-465 admin payments API 연동 및 전파거리 탭 URL 수정
  src/app/admin/zet-charge-logs/page.tsx
  src/app/signal/page.tsx
  src/backend/services/admin/zetRecovery.ts
  src/backend/types/zetRecovery.ts
  src/constants/api.ts
  src/shared/ui/Modal/SpaceMailModal.tsx
Labels: enhancement
